title: Introduction to PyTorch Lightning
author: Lightning.ai
created: 2020-12-21
license: CC BY-SA
tags:
  - Image
description: In this notebook, we'll go over the basics of lightning by preparing
  models to train on the [MNIST Handwritten Digits dataset](https://en.wikipedia.org/wiki/MNIST_database).
accelerator:
  - CPU
  - GPU
