trigger:
  branches:
    include: ["main"]
  paths:
    include:
      - ".azure/docker-build.yml"
      - "_dockers/**"
      - "_requirements/*.txt"
      - "requirements.txt"

pr:
  branches:
    include: ["*"]
  paths:
    include:
      - ".azure/docker-build.yml"
      - "_dockers/**"
      - "_requirements/*.txt"
      - "requirements.txt"
    exclude:
      - "*.md"
      - "**/*.md"

jobs:
  - job: build_push
    # how much time to give 'run always even if cancelled tasks' before stopping them
    cancelTimeoutInMinutes: "2"
    timeoutInMinutes: "95"
    variables:
      UBUNTU_VERSION: "22.04"
      CUDA_VERSION: "12.1.1"
      PYTHON_VERSION: "3.10"
      imageRepository: "pytorchlightning/tutorials"
      imageTag: "ubuntu$(UBUNTU_VERSION)-cuda$(CUDA_VERSION)-py$(PYTHON_VERSION)"
    pool: "lit-rtx-3090"
    workspace:
      clean: all
    steps:
      - bash: |
          set -e
          echo $imageTag
          nvidia-smi
          docker image build \
            -t $(imageRepository):$(imageTag) \
            -f "_dockers/ubuntu-cuda/Dockerfile" \
            --build-arg UBUNTU_VERSION="$(UBUNTU_VERSION)" \
            --build-arg CUDA_VERSION="$(CUDA_VERSION)" \
            --build-arg PYTHON_VERSION="$(PYTHON_VERSION)" \
            . --no-cache
        timeoutInMinutes: "95"
        displayName: "Build base image"

      - bash: |
          set -e
          echo $(imageRepository):$(imageTag)
          echo $(DOCKERHUB_PAT) | docker login --username $(DOCKERHUB_USER) --password-stdin
          docker push $(imageRepository):$(imageTag)
        condition: ne(variables['Build.Reason'], 'PullRequest')
        timeoutInMinutes: "35"
        displayName: "Push base image"
