blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/Lightning-AI/tutorials/discussions/new
    about: Ask and answer Lightning related questions
  - name: 💬 Discord
    url: https://discord.com/invite/tfXFetEZxv
    about: Chat with our community
