title: PyTorch Lightning Basic GAN Tutorial
author: Lightning.ai
created: 2020-12-21
license: CC BY-SA
tags:
  - Image
description: |
  How to train a GAN!

  Main takeaways:
  1. Generator and discriminator are arbitrary PyTorch modules.
  2. training_step does both the generator and discriminator training.
accelerator:
  - CPU
  - GPU
