title: PyTorch Lightning CIFAR10 ~94% Baseline Tutorial
author: Lightning.ai
created: 2020-12-21
license: CC BY-SA
tags:
  - Image
description: >
  Train a Resnet to 94% accuracy on Cifar10!
accelerator:
  - GPU
